"""update tuningstatus enum

Revision ID: 76d245e2676e
Revises: 45cb02442888
Create Date: 2025-05-24 21:25:34.722366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76d245e2676e'
down_revision: Union[str, None] = '45cb02442888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trial_usages_id', table_name='trial_usages')
    op.drop_table('trial_usages')
    op.alter_column('job_descriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_descriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('job_descriptions_resume_id_fkey', 'job_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'job_descriptions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job_descriptions', 'is_hired')
    op.drop_column('job_descriptions', 'interview_notes')
    op.drop_column('job_descriptions', 'interview_status')
    op.drop_column('job_descriptions', 'company_name')
    op.drop_column('job_descriptions', 'interview_date')
    op.drop_column('job_descriptions', 'hire_date')
    op.drop_column('job_descriptions', 'position_title')
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resumes', 'original_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tuned_resumes', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tuned_resumes', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tuned_resumes', 'status',
               existing_type=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ERROR', name='tuningstatus'),
               nullable=True)
    op.alter_column('tuned_resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tuned_resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('tuned_resumes', 'metadata')
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_tokens', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_tokens', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tuned_resumes', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('tuned_resumes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tuned_resumes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tuned_resumes', 'status',
               existing_type=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ERROR', name='tuningstatus'),
               nullable=False)
    op.alter_column('tuned_resumes', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tuned_resumes', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resumes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('resumes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'original_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('job_descriptions', sa.Column('position_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('hire_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('interview_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('interview_status', postgresql.ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED', 'OFFER_RECEIVED', 'HIRED', name='interviewstatus'), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('interview_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('is_hired', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.create_foreign_key('job_descriptions_resume_id_fkey', 'job_descriptions', 'resumes', ['resume_id'], ['id'])
    op.alter_column('job_descriptions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('job_descriptions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('trial_usages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trial_usages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trial_usages_pkey')
    )
    op.create_index('ix_trial_usages_id', 'trial_usages', ['id'], unique=False)
    # ### end Alembic commands ###
