"""add_cover_letter_field

Revision ID: eb9002c751c0
Revises: add_account_type
Create Date: 2025-03-14 14:53:22.122531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9002c751c0'
down_revision: Union[str, None] = 'add_account_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuned_resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuned_resumes', schema=None) as batch_op:
        batch_op.drop_column('cover_letter')
    # ### end Alembic commands ###
